name: Build and Deploy

on:
  push:
    branches:
      - feature/taj  # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: runner-1  # Use the label of your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true  # Replace with your build command (e.g., gradle build)
          #working-directory: path/to/maven/project  # Replace with the path to your Maven project

      - name: Deploy to Tomcat
        run: |
          sudo cp **/*.war /opt/tomcat/webapps/  # Replace path/to/maven/project with the actual path to your Maven project
          sudo systemctl restart tomcat

      - name: Get the latest release tag
        id: get_latest_tag
        uses: actions/github-script@v4
        with:
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            if (releases.length > 0) {
              console.log(releases[0].tag_name);
              core.setOutput("latest_tag", releases[0].tag_name);
            } else {
              console.log("No releases found.");
              core.setOutput("latest_tag", "v1.0.0");  // Set the initial tag to v1.0.0
            }

      - name: Increment tag
        id: increment_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          IFS='.' read -r major minor patch <<< "$latest_tag"
          next_tag="$major.$minor.$((patch + 1))"
          echo "::set-output name=next_tag::$next_tag"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.increment_tag.outputs.next_tag }}
          release_name: Release ${{ steps.increment_tag.outputs.next_tag }}
          body: |
            Add release notes here # Replace with the release notes for the new version
          draft: false
          prerelease: false
          files: |
            **/*.war  # Replace path/to/maven/project with the actual path to your Maven project

